sugarcube-2:

  macros:

    storyletsinit:
      name: storyletsinit
      description: |
        *Syntax*: `<<storyletsinit [store name]>>`

        The `<<storyletsinit>>` macro sets up the storylet tracking variables for a particular store. If you do not pass a store name as the argument, it will set up the default "storylets" store. You must call this macro at least once before using MQBN, normally this will be in the StoryInit special passage.

        You can also use the name `<<initstorylets>>` for this macro.

      parameters:
      - '|+ text'



    initstorylets:
      name: initstorylets
      description: |
        *Syntax*: `<<initstorylets [store name]>>`

        The `<<initstorylets>>` macro sets up the storylet tracking variables for a particular store. If you do not pass a store name as the argument, it will set up the default "storylets" store. You must call this macro at least once before using MQBN, normally this will be in the StoryInit special passage.

        You can also use the name `<<storyletsinit>>` for this macro.

      parameters:
      - '|+ text'



    storyletsprune:
      name: storyletsprune
      description: |
        *Syntax*: `<<storyletsprune [store name]>>`

        The `<<storyletsprune>>` macro deletes all used storylets from the given store, so that they will no longer be checked when you call MQBN.getStorylets(). You do not need to do this, but if your storylet store is very large, you may wish to do so to reduce computation time.

        Note that since storylet stores are part of setup, reloading the game will undo the pruning. For this reason, you may want to add `<<storyletsprune>>` to the StoryInit special passage, after the store is defined.

        You can also use the name `<<prunestorylets>>` for this macro.

      parameters:
      - '|+ text'



    prunestorylets:
      name: prunestorylets
      description: |
        *Syntax*: `<<prunestorylets [store name]>>`

        The `<<prunestorylets>>` macro deletes all used storylets from the given store, so that they will no longer be checked when you call MQBN.getStorylets(). You do not need to do this, but if your storylet store is very large, you may wish to do so to reduce computation time.

        Note that since storylet stores are part of setup, reloading the game will undo the pruning. For this reason, you may want to add `<<prunestorylets>>` to the StoryInit special passage, after the store is defined.

        You can also use the name `<<storyletsprune>>` for this macro.

      parameters:
      - '|+ text'



    storyletscan:
      name: storyletscan
      description: |
        *Syntax*: `<<storyletscan>>`

        The `<<storyletscan>>` macro scans the game's passages for `<<storylet>>` macros and turns their contents into storylets, which it then adds to the specified store. You can use this macro to associate storylets with the passages they reference, which you may find easier to track than a separate list created elsewhere.

        You should almost certainly only call this macro in the StoryInit special passage.

      parameters:
      -



    storylet:
      name: storylet
      description: |
        *Syntax*: `<<storylet [store name]>>`

        The `<<storylet>>` macro allows you to define a storylet in the passage it corresponds to, rather than in your story javascript, or StoryInit. Use the `<<storyletscan>>` macro to scan for such storylets.

        The body of the `<<storylet>>` macro should either be a valid storylet object definition, a single twinescript expression, or a `<<cond>>` macro followed by a valid storylet object definition. If it's a twinescript expression, it will become a single tws condition. If it's a `<cond>>` followed by a storylet object, the `<<cond>>` becomes a single tws condition on the storylet.

        e.g.

                :: Harvest
                <<storylet>>
                    {
                        desc: "It is harvest time at the farm"
                    }
                <</storylet>>
                Text of the harvest passage ...


                :: Harvest
                <<storylet>>
                $season is "autumn"
                <</storylet>>
                Text of the harvest passage ...

        Becomes `{ all: [ { type: "tws", cond: '$season is "autumn"' }]}`

                :: Harvest
                <<storylet>>
                    <<cond>>$season is "autumn"<</cond>>
                    {
                        sticky: true
                    }
                <</storylet>>
                Text of the harvest passage ...

        Becomes `{ sticky: true, all: [ { type: "tws", cond: '$season is "autumn"' }]}`

        The `<<storylet>>` macro should only contain one storylet. If you don't specify the storylet title, it defaults to the passage title. If you do, the storylet's passage is set to the passage name instead. If you don't specity the optional store name, the storylet will be added to the "storylets" store.

      parameters:
      - "|+ text"
      container: true
      children: ["cond"]



    cond:
      name: cond
      description: |
        *Syntax*: `<<storylet [store name]>>`

        The `<<storylet>>` macro allows you to define a storylet in the passage it corresponds to, rather than in your story javascript, or StoryInit. Use the `<<storyletscan>>` macro to scan for such storylets.

        The body of the `<<storylet>>` macro should either be a valid storylet object definition, a single twinescript expression, or a `<<cond>>` macro followed by a valid storylet object definition. If it's a twinescript expression, it will become a single tws condition. If it's a `<cond>>` followed by a storylet object, the `<<cond>>` becomes a single tws condition on the storylet.

        e.g.

                :: Harvest
                <<storylet>>
                    {
                        desc: "It is harvest time at the farm"
                    }
                <</storylet>>
                Text of the harvest passage ...


                :: Harvest
                <<storylet>>
                $season is "autumn"
                <</storylet>>
                Text of the harvest passage ...

        Becomes `{ all: [ { type: "tws", cond: '$season is "autumn"' }]}`

                :: Harvest
                <<storylet>>
                    <<cond>>$season is "autumn"<</cond>>
                    {
                        sticky: true
                    }
                <</storylet>>
                Text of the harvest passage ...

        Becomes `{ sticky: true, all: [ { type: "tws", cond: '$season is "autumn"' }]}`

        The `<<storylet>>` macro should only contain one storylet. If you don't specify the storylet title, it defaults to the passage title. If you do, the storylet's passage is set to the passage name instead. If you don't specity the optional store name, the storylet will be added to the "storylets" store.

      parameters:
      -
      container: true
      parents: ["storylet"]



    storyletgoto:
      name: storyletgoto
      description: |
        *Syntax*: `<<storyletgoto storyletname-or-object [store "store name"] [open true|false]>>`

        The `<<storyletgoto>>` macro sends you to the passage corresponding to the storylet given in the first argument, marks that storylet as used, and fires the `:storyletchosen` event.

        You can specify the storylet by passing a valid storylet object (e.g. one returned from `MQBN.getStorylets()`), in which case the storylet is not checked for validity (i.e. it can be already played, not meeting the requirments etc.). Alternatively you can specify the storylet by name or id. In this case the storylet is checked for availability if you specify open true in the arguments.

        If you supply a name that matches multiple storylet titles, then the first storylet matching that title (or the first open one, if you specify open true) is used.

        e.g.

                <<link "Goto an object">>
                    <<set _story = MQBN.getStorylets(1)[0]>>
                    <<storyletgoto _story>>
                <</link>>
                <<link "Goto by name">>
                    <<storyletgoto "farm-event" open true>>
                <</link>>

      parameters:
      - text |+ ("store" &+ text) |+ ("open" &+ bool)



    storyletinclude:
      name: storyletinclude
      description: |
        *Syntax*: `<<storyletinclude storyletname-or-object [store "store name"] [open true|false]>>`

        The storylet version of `<<include>>`. Given a storylet object or name, includes that storylet's passage's contents into the current passage. This marks the storylet used, just as if you had gone to it with `<<storyletgoto>>` or `<<storyletlink>>`.

        You can specify the storylet by passing a valid storylet object (e.g. one returned from `MQBN.getStorylets()`), in which case the storylet is not checked for validity (i.e. it can be already played, not meeting the requirments etc.). Alternatively you can specify the storylet by name or id. In this case the storylet is checked for availability if you specify open true in the arguments.

        If you supply a name that matches multiple storylet titles, then the first storylet matching that title (or the first open one, if you specify open true) is used.

        e.g.

                <<set _story = MQBN.getStorylets(1)[0]>>
                <<storyletinclude _story>>

      parameters:
      - text |+ ("store" &+ text) |+ ("open" &+ bool)



    storyletlink:
      name: storyletlink
      description: |
        *Syntax*: `<<storyletlink storyletname-or-object [store "store name"] [behaviour disabled|hidden] [text "link text"] [disabled-text "link text"]>><</storyletlink>>`

        The `<<storyletlink>>` macro creates a link to a storylet passage. When clicked it runs its contents (like `<<link>>` does), navigates to the passage corresponding to the storylet given in the first argument, marks that storylet as used, and fires the `:storyletchosen` event.

        If the first argument is a storylet object, the macro will always create a link to that storylet, without checking if it is available or not. The link's title will be the storylet's link attribute, or title if it doesn't have one. You can override this by supplying your own title with the text argument.

        e.g.

                <<set _story = MQBN.getStorylets(1)[0]>>
                <<storyletlink _story text "See what happens">><</storylet>>

        If the first argument is a storylet name, the macro makes a link to that storylet. If the storylet is available, the link functions like the object version, however if the storylet is not available, the behaviour depends on the behaviour argument. If behaviour is "hidden" (the default), the link does not show. If behaviour is "disabled" it will show a disabled link instead. You can specify different text for the disabled link with the disabed-text argument.

        e.g.

                <<storyletlink "Visit the Farm" behaviour "disabled" disabled-text "No More Farm">><</storyletlink>>

      parameters:
      - text |+ ("store" &+ text) |+ ("behaviour" &+ ("disabled" | "hidden")) |+ ("text" &+ text) |+ ("disabled-text" &+ text)
      container: true



    storyletuse:
      name: storyletuse
      description: |
        *Syntax*: `<<storyletuse storyletname-or-object [store "store name"]>>`

        The `<<storyletuse>>` macro marks a storylet as used, which means it will no-longer be returned by `MQBN.getStorylets()` (unless it is sticky), and fires the `:storyletchosen` event. You can use `<<storyletuse>>` where you don't want to use `<<storyletgoto>>` or `<<storyletlink>>` to do this automatically.
      parameters:
      - text |+ ("store" &+ text)




    sequence:
      name: sequence
      description: |
        *Syntax*: `<<sequence "$varname" "cycling|linear" [values]>>`

        The `<<sequence>>` macro sets up a sequence. You must set up each sequence before you use it, so its normal to place `<<sequence>>` in the StoryInit special passage. Each sequence has a name, which is the name of the variable that holds it, and a set of values, which are what you can advance through.

        e.g.

                <<sequence "$season" cycling "Spring" "Summer" "Autumn" "Winter">>

        By default a sequence is "linear", which means that advancing it when it has reached the end, does nothing. If you specify that the sequence is "cycling", then advancing it when it is on its last value returns to the beginning. The same happens in the opposite direction if you rewind it.

        The values supplied to the `<<sequence>>` macro can be supplied as an array:

                <<set _seasons = ["Spring", "Summer", "Autumn", "Winter"]>>
                <<sequence "$season" cycling _seasons>>

        You can supply an explcit numerical value for each name by passing an object instead of an array:

                <<set _levels = { 1: "level 1", 100: "level 2", 300: "level 3", 1000: "level 4" }>>
                <<sequence "$level" linear _levels>>

        In this way you could track XP ($level.value) and the corresponding level ($level).

        If you place the related story variable in a sting context (e.g. `<<=$season>>`) you will get the name. You can access the value with `$season.value`. You can also explicitly get the name with `$season.name`.
      parameters:
      - text &+ ("cycling" | "linear") |+ ...text



    sequenceadvance:
      name: sequenceadvance
      description: |
        *Syntax*: `<<sequenceadvance "$sequence" [steps]>>`

        The `<<sequenceadvance>>` and `<<sequencerewind>>` macros advance or rewind a given sequence, usually by one step, but you can specify a different number of steps with the optional argument. e.g. `<<sequenceadvance "$season" 2>>`.

        Each time a cycling sequence resets to the start with `<<sequenceadvance>>`, a counter is incremented to track how many times through the sequence you have progressed. You can access this with $sequencename.count (e.g. $season.count). The same happens in reverse with `<<sequencerewind>>`.
      parameters:
      - text |+ number


    sequencerewind:
      name: sequencerewind
      description: |
        *Syntax*: `<<sequencerewind "$sequence" [steps]>>`

        The `<<sequenceadvance>>` and `<<sequencerewind>>` macros advance or rewind a given sequence, usually by one step, but you can specify a different number of steps with the optional argument. e.g. `<<sequenceadvance "$season" 2>>`.

        Each time a cycling sequence resets to the start with `<<sequenceadvance>>`, a counter is incremented to track how many times through the sequence you have progressed. You can access this with $sequencename.count (e.g. $season.count). The same happens in reverse with `<<sequencerewind>>`.
      parameters:
      - text |+ number
